import { motion } from 'framer-motion';
import { Brain, TrendingUp, MessageSquare, Stethoscope, Info } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { LineChart, Line, ResponsiveContainer, YAxis } from 'recharts';
import type { MentalHealthSnapshot as SnapshotType } from '@/lib/types/profile';
import { profileSectionCard } from '@/components/profile/profileSurface';
import { cn } from '@/lib/utils';

interface MentalHealthSnapshotProps {
    snapshot: SnapshotType | null;
    loading: boolean;
}

const trendEmoji: Record<string, string> = {
    improving: '📈',
    stable: '➡️',
    declining: '📉',
};

const trendColor: Record<string, string> = {
    improving: 'text-success',
    stable: 'text-warning',
    declining: 'text-danger',
};

export function MentalHealthSnapshot({ snapshot, loading }: MentalHealthSnapshotProps) {
    if (loading) {
        return (
            <Card className={cn(profileSectionCard, 'overflow-hidden')}>
                <CardHeader>
                    <Skeleton className="h-6 w-56" />
                </CardHeader>
                <CardContent className="space-y-4">
                    <Skeleton className="h-20 w-full rounded-xl" />
                    <Skeleton className="h-12 w-full rounded-xl" />
                    <Skeleton className="h-12 w-full rounded-xl" />
                </CardContent>
            </Card>
        );
    }

    if (!snapshot) return null;

    return (
        <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ type: 'spring', stiffness: 40, damping: 38, mass: 1.2, delay: 0.08 }}
        >
            <Card className={cn(profileSectionCard, 'overflow-hidden')}>
                <CardHeader className="pb-4">
                    <div className="flex items-center justify-between">
                        <div className="min-w-0">
                            <p className="text-[11px] font-medium uppercase tracking-[0.2em] text-ink-5">Overview</p>
                            <CardTitle className="mt-1 flex items-center gap-2 font-display text-xl font-normal tracking-tight text-ink-8">
                                <Brain className="h-5 w-5 text-[hsl(var(--accent-500))]" strokeWidth={1.8} />
                                How things have been feeling
                            </CardTitle>
                        </div>
                        <Tooltip>
                            <TooltipTrigger>
                                <Info className="h-4 w-4 text-muted-foreground hover:text-primary transition-colors" />
                            </TooltipTrigger>
                            <TooltipContent side="left" className="max-w-[260px]">
                                <p className="text-xs">
                                    This summary is auto-generated by MindMitra so a therapist can read the shape of how you've been.
                                    It is never shared without your permission.
                                </p>
                            </TooltipContent>
                        </Tooltip>
                    </div>
                    <p className="text-sm text-ink-6 leading-relaxed">
                        A soft summary — only shared when you say it's okay.
                    </p>
                </CardHeader>

                <CardContent className="space-y-5">
                    {/* Stress Triggers */}
                    {snapshot.stress_triggers.length > 0 && (
                        <div className="space-y-2">
                            <p className="text-[13px] font-medium text-ink-6">
                                Themes that showed up
                            </p>
                            <div className="flex flex-wrap gap-2">
                                {snapshot.stress_triggers.map(trigger => (
                                    <Badge
                                        key={trigger}
                                        variant="secondary"
                                        className="bg-primary/8 text-primary border-primary/15 rounded-xl px-3 py-1 text-xs"
                                    >
                                        {trigger}
                                    </Badge>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Emotional Trend */}
                    <div className="flex items-center justify-between rounded-xl border border-ink-3/40 bg-[hsl(var(--ink-1))] p-4 dark:bg-[hsl(var(--ink-2))]/80">
                        <div className="space-y-1">
                            <p className="text-[13px] font-medium text-ink-6">
                                Emotional rhythm
                            </p>
                            <p className={`text-sm font-semibold capitalize ${trendColor[snapshot.emotional_trend]}`}>
                                {snapshot.emotional_trend} {trendEmoji[snapshot.emotional_trend]}
                            </p>
                        </div>

                        {/* Sparkline Chart */}
                        {snapshot.trend_data.length > 0 && (
                            <div className="w-24 h-10">
                                <ResponsiveContainer width="100%" height="100%">
                                    <LineChart data={snapshot.trend_data}>
                                        <YAxis domain={['dataMin - 5', 'dataMax + 5']} hide />
                                        <Line
                                            type="monotone"
                                            dataKey="score"
                                            stroke="var(--primary)"
                                            strokeWidth={2}
                                            dot={false}
                                        />
                                    </LineChart>
                                </ResponsiveContainer>
                            </div>
                        )}
                    </div>

                    {/* Sessions */}
                    <div className="flex items-center gap-3 rounded-xl border border-ink-3/40 bg-[hsl(var(--ink-1))] p-4 dark:bg-[hsl(var(--ink-2))]/80">
                        <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[hsl(var(--accent-100))]/60 dark:bg-[hsl(var(--accent-100))]/20">
                            <MessageSquare className="h-5 w-5 text-[hsl(var(--accent-600))] dark:text-[hsl(var(--accent-400))]" strokeWidth={1.8} />
                        </div>
                        <div>
                            <p className="text-sm font-semibold text-foreground">
                                {snapshot.sessions_completed} conversations
                            </p>
                            <p className="text-xs text-muted-foreground">
                                Sessions completed with MindMitra
                            </p>
                        </div>
                    </div>

                    {/* Therapist Connection */}
                    <div className="flex items-center gap-3 rounded-xl border border-ink-3/40 bg-[hsl(var(--ink-1))] p-4 dark:bg-[hsl(var(--ink-2))]/80">
                        <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[hsl(var(--warmth-100))]/50 dark:bg-[hsl(var(--warmth-100))]/15">
                            <Stethoscope className="h-5 w-5 text-[hsl(var(--warmth-500))] dark:text-[hsl(var(--warmth-400))]" strokeWidth={1.8} />
                        </div>
                        <div>
                            <p className="text-sm font-semibold text-foreground">
                                {snapshot.therapist_name
                                    ? `Connected with ${snapshot.therapist_name}`
                                    : 'Not connected yet'}
                            </p>
                            <p className="text-xs text-muted-foreground">
                                {snapshot.therapist_name
                                    ? 'Your therapist can view your wellness summary'
                                    : 'Connect with a therapist through Therapist Bridge'}
                            </p>
                        </div>
                    </div>

                    {/* Disclaimer */}
                    <p className="text-xs text-muted-foreground/70 text-center italic pt-2">
                        A small map of how you've been — never shared without your consent.
                    </p>
                </CardContent>
            </Card>
        </motion.div>
    );
}
