import { motion } from 'framer-motion';
import { Brain, TrendingUp, MessageSquare, Stethoscope, Info } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { LineChart, Line, ResponsiveContainer, YAxis } from 'recharts';
import type { MentalHealthSnapshot as SnapshotType } from '@/lib/types/profile';

interface MentalHealthSnapshotProps {
    snapshot: SnapshotType | null;
    loading: boolean;
}

const trendEmoji: Record<string, string> = {
    improving: '📈',
    stable: '➡️',
    declining: '📉',
};

const trendColor: Record<string, string> = {
    improving: 'text-success',
    stable: 'text-warning',
    declining: 'text-danger',
};

export function MentalHealthSnapshot({ snapshot, loading }: MentalHealthSnapshotProps) {
    if (loading) {
        return (
            <Card className="bg-surface border-border shadow-sm rounded-2xl">
                <CardHeader>
                    <Skeleton className="h-6 w-56" />
                </CardHeader>
                <CardContent className="space-y-4">
                    <Skeleton className="h-20 w-full rounded-xl" />
                    <Skeleton className="h-12 w-full rounded-xl" />
                    <Skeleton className="h-12 w-full rounded-xl" />
                </CardContent>
            </Card>
        );
    }

    if (!snapshot) return null;

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
        >
            <Card className="bg-surface border-border shadow-sm rounded-2xl">
                <CardHeader className="pb-4">
                    <div className="flex items-center justify-between">
                        <CardTitle className="text-lg font-semibold text-foreground flex items-center gap-2">
                            <Brain className="h-5 w-5 text-primary" />
                            My Wellness Snapshot
                        </CardTitle>
                        <Tooltip>
                            <TooltipTrigger>
                                <Info className="h-4 w-4 text-muted-foreground hover:text-primary transition-colors" />
                            </TooltipTrigger>
                            <TooltipContent side="left" className="max-w-[260px]">
                                <p className="text-xs">
                                    This summary is auto-generated by MindMitra to help your therapist understand your journey better.
                                    It is never shared without your permission.
                                </p>
                            </TooltipContent>
                        </Tooltip>
                    </div>
                    <p className="text-sm text-muted-foreground">
                        A gentle overview of your mental wellness journey 🌿
                    </p>
                </CardHeader>

                <CardContent className="space-y-5">
                    {/* Stress Triggers */}
                    {snapshot.stress_triggers.length > 0 && (
                        <div className="space-y-2">
                            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                                Areas we've noticed
                            </p>
                            <div className="flex flex-wrap gap-2">
                                {snapshot.stress_triggers.map(trigger => (
                                    <Badge
                                        key={trigger}
                                        variant="secondary"
                                        className="bg-primary/8 text-primary border-primary/15 rounded-xl px-3 py-1 text-xs"
                                    >
                                        {trigger}
                                    </Badge>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Emotional Trend */}
                    <div className="flex items-center justify-between bg-background/50 rounded-xl p-4 border border-border/50">
                        <div className="space-y-1">
                            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                                Emotional Trend
                            </p>
                            <p className={`text-sm font-semibold capitalize ${trendColor[snapshot.emotional_trend]}`}>
                                {snapshot.emotional_trend} {trendEmoji[snapshot.emotional_trend]}
                            </p>
                        </div>

                        {/* Sparkline Chart */}
                        {snapshot.trend_data.length > 0 && (
                            <div className="w-24 h-10">
                                <ResponsiveContainer width="100%" height="100%">
                                    <LineChart data={snapshot.trend_data}>
                                        <YAxis domain={['dataMin - 5', 'dataMax + 5']} hide />
                                        <Line
                                            type="monotone"
                                            dataKey="score"
                                            stroke="var(--primary)"
                                            strokeWidth={2}
                                            dot={false}
                                        />
                                    </LineChart>
                                </ResponsiveContainer>
                            </div>
                        )}
                    </div>

                    {/* Sessions */}
                    <div className="flex items-center gap-3 bg-background/50 rounded-xl p-4 border border-border/50">
                        <div className="h-10 w-10 rounded-xl bg-accent/10 flex items-center justify-center">
                            <MessageSquare className="h-5 w-5 text-accent" />
                        </div>
                        <div>
                            <p className="text-sm font-semibold text-foreground">
                                {snapshot.sessions_completed} conversations
                            </p>
                            <p className="text-xs text-muted-foreground">
                                Sessions completed with MindMitra
                            </p>
                        </div>
                    </div>

                    {/* Therapist Connection */}
                    <div className="flex items-center gap-3 bg-background/50 rounded-xl p-4 border border-border/50">
                        <div className="h-10 w-10 rounded-xl bg-secondary/10 flex items-center justify-center">
                            <Stethoscope className="h-5 w-5 text-secondary" />
                        </div>
                        <div>
                            <p className="text-sm font-semibold text-foreground">
                                {snapshot.therapist_name
                                    ? `Connected with ${snapshot.therapist_name}`
                                    : 'Not connected yet'}
                            </p>
                            <p className="text-xs text-muted-foreground">
                                {snapshot.therapist_name
                                    ? 'Your therapist can view your wellness summary'
                                    : 'Connect with a therapist through Therapist Bridge'}
                            </p>
                        </div>
                    </div>

                    {/* Disclaimer */}
                    <p className="text-xs text-muted-foreground/70 text-center italic pt-2">
                        This snapshot is generated to help you on your journey — it's never shared without your consent.
                    </p>
                </CardContent>
            </Card>
        </motion.div>
    );
}
