// GENERATED by scripts/optimize-river-images.mjs — do not edit by hand.
// Re-run the script against the source art to regenerate.
//
// Filenames are content-hashed; Vite serves them immutable, so a changed image
// only reaches users under a new name.
//
// `lqip` is a ~20px WebP inlined as a data URI. RiverImage paints it as a
// background under the real image, so a loading tile shows the painting's
// colours instead of an empty box. It is ~200 bytes; do not grow it into a
// second image budget.

export interface RiverImageEntry {
  /** width (px) → filename */
  readonly avif: Readonly<Record<number, string>>;
  readonly webp: Readonly<Record<number, string>>;
  /** intrinsic size of the largest variant, for aspect-ratio reservation */
  readonly width: number;
  readonly height: number;
  /** ~20px WebP data URI painted while the real image loads */
  readonly lqip: string;
}

export const RIVER_MANIFEST = {
  "door-bridge-dark": {
    "avif": {
      "256": "door-bridge-dark-256.fa23bb6d.avif",
      "640": "door-bridge-dark-640.7c5ca1df.avif"
    },
    "webp": {
      "256": "door-bridge-dark-256.cdc560c1.webp",
      "640": "door-bridge-dark-640.be027580.webp"
    },
    "width": 640,
    "height": 640,
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACQBACdASoUABQAPt1kqE+opaOiKAqpEBuJYwCo9BERMVsJb8b1JadGtcJ5KgAA/uzXLTZNGqtLZIadQimQeZ7DL1Rd3LUq67ePsLuqxLVGxc3ez0zItpr64pWujjmaSsdCfRz2RFtk1sO26sX3fmdc0craOKqx3wnDlWAAAAA="
  },
  "door-bridge": {
    "avif": {
      "256": "door-bridge-256.f37de69b.avif",
      "640": "door-bridge-640.0014cc4c.avif"
    },
    "webp": {
      "256": "door-bridge-256.7bdeed72.webp",
      "640": "door-bridge-640.8881f847.webp"
    },
    "width": 640,
    "height": 640,
    "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABwBACdASoUABQAPt1ipU8opaMiKA1REBuJZQC+SBEOag66uiQKz+shm8ULgAD+8c102S+ELn2BrMAJw0yOMsXpjDZ72CGTARsALHn3xk/wJTjJ0OSqZ1WInJGB/EMHd2V9eu+7wVoWsk5nY/WsRG8u3+Rh7gBDW+6UpHWRCcAAAA=="
  },
  "door-diya-dark": {
    "avif": {
      "256": "door-diya-dark-256.0c8fe6ce.avif",
      "640": "door-diya-dark-640.f9aea467.avif"
    },
    "webp": {
      "256": "door-diya-dark-256.42979818.webp",
      "640": "door-diya-dark-640.6af16daf.webp"
    },
    "width": 640,
    "height": 640,
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABQBACdASoUABQAPt1ipk8opaMiKA1REBuJYwAAIymiOLBP1K5VsNujXfp4AP7r/ySsgu6apxn7MU7r3AqvZdkIuvZt4GZF432PlOO0j9vtszr6+FP14brH5nvBINrJESS7QhmSDhvq6/2NaFbDaY+mybPskDX7jxRiAAAA"
  },
  "door-diya": {
    "avif": {
      "256": "door-diya-256.d2c5f53b.avif",
      "640": "door-diya-640.0c66eb7e.avif"
    },
    "webp": {
      "256": "door-diya-256.76595c63.webp",
      "640": "door-diya-640.9e6badc8.webp"
    },
    "width": 640,
    "height": 640,
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACwBACdASoUABQAPt1iq08opSQiKAqpEBuJYwAALnWOT/M1lKnrRwVUrp62zKtAAP7tN1W/YYU4mRDJ9NTnwTMnIyLtb0LFfj9vftAlH8UwqwwIqKarwT3H0YA82lEo4lYW3YETNvUKw9pL4sn6gZI4AAA="
  },
  "door-journal-dark": {
    "avif": {
      "256": "door-journal-dark-256.825f1678.avif",
      "640": "door-journal-dark-640.52b859a0.avif"
    },
    "webp": {
      "256": "door-journal-dark-256.ffa416b1.webp",
      "640": "door-journal-dark-640.e8514fbc.webp"
    },
    "width": 640,
    "height": 640,
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwBQCdASoUABQAPt1mq1CopSOiqAgBEBuJYwCxHzRA2BLR1jx8Gcr6FBhEQhpuwSYuxXnAAP7u5ITrJjEC3NOnCxP7OL1AVYSRM3e4t0UVd3RmXO8rpJZ7fd4VBumVa6MB2ZH4XMYrR/Lrcas2gCl16pM1bixhP6l6o/J5XMw43EEkPEou3OicDBAAAA=="
  },
  "door-journal": {
    "avif": {
      "256": "door-journal-256.8ab30c96.avif",
      "640": "door-journal-640.2b3f9619.avif"
    },
    "webp": {
      "256": "door-journal-256.566a6fc3.webp",
      "640": "door-journal-640.ff0c500c.webp"
    },
    "width": 640,
    "height": 640,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABwBACdASoUABQAPt1gp04opaMiKA1REBuJZQAAFrMIVT1pA1MVw3kXucAMoAD+aDyZt/bueVbLeCTU+B923+Ed4z+mZvXhq2Dvk1WqjQEg1Vc6l24+sPuTreDpPMDMF0dqWEdzrEJBR8sf2U8pp1VROqFXb3zjboeKWkx23BLHNVG0SfojtNyP12SPnerAAAA="
  },
  "door-mindgym-dark": {
    "avif": {
      "256": "door-mindgym-dark-256.554fc954.avif",
      "640": "door-mindgym-dark-640.94d64760.avif"
    },
    "webp": {
      "256": "door-mindgym-dark-256.5e45bef2.webp",
      "640": "door-mindgym-dark-640.0d5168e0.webp"
    },
    "width": 640,
    "height": 640,
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwBQCdASoUABQAPt1iqE+opSOiKAqpEBuJYwCdMtDBtRjbOh38TnDDla/gzFJhB9AwAAD+8Q/EDAk7+OIfOOpXtBD7qz2w/1sMQHLOnURyhQsxD3gxe3U9CyvtP3PDEHrxO7pjU8Y+DlOr9SxnuBX4DtrrxB94AAA="
  },
  "door-mindgym": {
    "avif": {
      "256": "door-mindgym-256.a4894b56.avif",
      "640": "door-mindgym-640.be4bcc4a.avif"
    },
    "webp": {
      "256": "door-mindgym-256.59180e3d.webp",
      "640": "door-mindgym-640.bd76eaf6.webp"
    },
    "width": 640,
    "height": 640,
    "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADQBACdASoUABQAPt1kqE+opaOiKAqpEBuJZQCBBAQE5kHaBLV7mHatUzG1OB4KAAD+mVMy04iEKUtbHZod2hHhxNkPLKLlK5z/ByyHrBHRmIo737DLBtceBgBT8owioEdsmgPzuqvatMdog0SXZjN9+r/ym1PihxI56EBSQAA="
  },
  "door-peer-dark": {
    "avif": {
      "256": "door-peer-dark-256.ca2898f6.avif",
      "640": "door-peer-dark-640.e6f71ce3.avif"
    },
    "webp": {
      "256": "door-peer-dark-256.a41f91ce.webp",
      "640": "door-peer-dark-640.845b03a0.webp"
    },
    "width": 640,
    "height": 640,
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACQBACdASoUABQAPt1mrFEopSQiqAgBEBuJZQCsABEONAsF3epQ0CSaMvwQgAAA/u7mmCJgNmjmpoQ9W3wRoTBTDxgKtGumsksncpjydDJNf88d5u0WtHNIF/+0547F2JDe32ncysjRFGNSIddREkZHGXUDTOEkAAA="
  },
  "door-peer": {
    "avif": {
      "256": "door-peer-256.2c6cc802.avif",
      "640": "door-peer-640.91ac4724.avif"
    },
    "webp": {
      "256": "door-peer-256.96a3ce3b.webp",
      "640": "door-peer-640.2ccc53c0.webp"
    },
    "width": 640,
    "height": 640,
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASoUABQAPt1UqUyopCQiMBgMARAbiWMAAC5xVw6Dzz6SuNWOgnS9pQoAAP7v7O6MpzMnQAUtmpqKCV6M+Z8occ7EDDfBeczqXb7fPtAkImwEMHRYbtViXp1n9MUZq/AeDdB3vAXwCu/rKBkvPtE2k4VFxFrcAA=="
  },
  "door-practice-breath": {
    "avif": {
      "256": "door-practice-breath-256.6b97cbee.avif",
      "640": "door-practice-breath-640.0c663e46.avif"
    },
    "webp": {
      "256": "door-practice-breath-256.e7a5d71b.webp",
      "640": "door-practice-breath-640.4d7b3d6e.webp"
    },
    "width": 640,
    "height": 480,
    "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoUAA8APt1apkyopSOiMAgBEBuJZgCdACHgUcNNZS1PuA1gAP7zdQsYixK8G+IyaNR7Eri3kCrzpJfnigcuYX2RtpyrjFivh1ogRpX3MjkVILNn+hJ7pcTdT7iQyhwF6OygoaXpXeiKzkcxTigAAA=="
  },
  "door-practice-drift": {
    "avif": {
      "256": "door-practice-drift-256.655b7939.avif",
      "640": "door-practice-drift-640.94f116ef.avif"
    },
    "webp": {
      "256": "door-practice-drift-256.fb771f51.webp",
      "640": "door-practice-drift-640.960f0930.webp"
    },
    "width": 640,
    "height": 480,
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADwAwCdASoUAA8APt1cpkyopSOiMAgBEBuJagCxB1/AWJlIARapGu3AAP7ZLZfe9Ni+/CzhulG8rnYJZ6BlbwQR5/q01SWZhMGM3vn5nvpCIZRfoBnyCd5/anjrGQoHDqqr2KvfY92oDn/r4Thtd/qjl6wNNoNRk7TQPTRpvQPxKvAy8AA="
  },
  "door-reads-dark": {
    "avif": {
      "256": "door-reads-dark-256.f689a0e7.avif",
      "640": "door-reads-dark-640.e6aa2cdc.avif"
    },
    "webp": {
      "256": "door-reads-dark-256.55d442cb.webp",
      "640": "door-reads-dark-640.0c75ffb4.webp"
    },
    "width": 640,
    "height": 640,
    "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAwBQCdASoUABQAPt1mq1CopSOiqAgBEBuJQBWGargwCrjHhOULvmzxN6DXBzDHuPteAAD+6/8T31AxBOrD3eOlDx3py/qnYLRggirw3R2t1ULJoX235WBv4mf/dCpXQiAHA08vCfuW4ri32+FjbrIJUGsGRlEhLyiVRSpArOCbSUZJ7z3XLA//zAPPia1GAAA="
  },
  "door-reads": {
    "avif": {
      "256": "door-reads-256.e9c64af5.avif",
      "640": "door-reads-640.ed09ebbb.avif"
    },
    "webp": {
      "256": "door-reads-256.53502eea.webp",
      "640": "door-reads-640.96a417e9.webp"
    },
    "width": 640,
    "height": 640,
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwBACdASoUABQAPt1iqE+opSOiKAqpEBuJZQCnFBEadtWlas5BI1JWiWQz9wxAAP7rIzmeYeD8adQWH+2GyktSIGdjjmZLeqNlP2wDdGGI17bK5Eg/z3A+kaQEVg3MiXriMd1W5Rep34xTjFsJ2J0Y4VnDpV8vQCUJC1CeM6pfI+lTAbQRAAAA"
  },
  "hero-landscape-afternoon": {
    "avif": {
      "640": "hero-landscape-afternoon-640.7981b4b8.avif",
      "1264": "hero-landscape-afternoon-1264.8914f1c8.avif"
    },
    "webp": {
      "640": "hero-landscape-afternoon-640.b1ae8423.webp",
      "1264": "hero-landscape-afternoon-1264.9325ea3e.webp"
    },
    "width": 1264,
    "height": 848,
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoUAA0APt1apkyopSOiMAgBEBuJYgCdABt9WoQutX951YAA/uHRl9gKHIuAJT5owmi10CzcI9gXOUXm4FBCftp0hpWZwyWBSNy0B5TRDsn5chMmVj8SkPIXXjK4d6wAAAA="
  },
  "hero-landscape-evening": {
    "avif": {
      "640": "hero-landscape-evening-640.95f613a4.avif",
      "1264": "hero-landscape-evening-1264.d15a87a1.avif"
    },
    "webp": {
      "640": "hero-landscape-evening-640.1fd6125e.webp",
      "1264": "hero-landscape-evening-1264.70037779.webp"
    },
    "width": 1264,
    "height": 843,
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwBACdASoUAA0APt1apkyopSOiMAgBEBuJYgCdHX+gdV6q04K+8dX9/YAA/Xc4ojOj6jxoCaD8m+APL9111vpWqshsLLAE/WgpyODeOOlhJCAHy3EuAv1NXzqrPWILmbLy16gvB1pYAA=="
  },
  "hero-landscape-morning": {
    "avif": {
      "640": "hero-landscape-morning-640.3a37c55d.avif",
      "1264": "hero-landscape-morning-1264.1a7cbc93.avif"
    },
    "webp": {
      "640": "hero-landscape-morning-640.a273001e.webp",
      "1264": "hero-landscape-morning-1264.d02fe380.webp"
    },
    "width": 1264,
    "height": 848,
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoUAA0APt1cpkyopSOiMAgBEBuJYwCdACIftwt3qCJEDWoAAP7VxSu79UoQsWfQo1K+Cljhzn4s+kwGmF5Qyw1kKAI15pzDInfrvWtD/nKk9w6MODa6U86JAAA="
  },
  "hero-landscape-night": {
    "avif": {
      "640": "hero-landscape-night-640.e193316b.avif",
      "1264": "hero-landscape-night-1264.8c7ea1f2.avif"
    },
    "webp": {
      "640": "hero-landscape-night-640.06ed7de8.webp",
      "1264": "hero-landscape-night-1264.67e08ae4.webp"
    },
    "width": 1264,
    "height": 848,
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQAwCdASoUAA0APt1cpkyopSOiMAgBEBuJQBOgArpGW2L3EZsAAP7uob73rlU7OCSkKVAzjOLFoPmFTV5jFXiR/4MqU8uTre9nvypVnlxYSc6NV1og0yxCkYLeCiUbGXJlMagAAAA="
  }
} as const satisfies Record<string, RiverImageEntry>;

export type RiverImageName = keyof typeof RIVER_MANIFEST;
