// GENERATED by scripts/optimize-river-images.mjs — do not edit by hand.
// Re-run the script against the source art to regenerate.
//
// Filenames are content-hashed; Vite serves them immutable, so a changed image
// only reaches users under a new name.

export interface RiverImageEntry {
  /** width (px) → filename */
  readonly avif: Readonly<Record<number, string>>;
  readonly webp: Readonly<Record<number, string>>;
  /** intrinsic size of the largest variant, for aspect-ratio reservation */
  readonly width: number;
  readonly height: number;
}

export const RIVER_MANIFEST = {
  "door-bridge-dark": {
    "avif": {
      "256": "door-bridge-dark-256.fa23bb6d.avif",
      "640": "door-bridge-dark-640.7c5ca1df.avif"
    },
    "webp": {
      "256": "door-bridge-dark-256.cdc560c1.webp",
      "640": "door-bridge-dark-640.be027580.webp"
    },
    "width": 640,
    "height": 640
  },
  "door-bridge": {
    "avif": {
      "256": "door-bridge-256.f37de69b.avif",
      "640": "door-bridge-640.0014cc4c.avif"
    },
    "webp": {
      "256": "door-bridge-256.7bdeed72.webp",
      "640": "door-bridge-640.8881f847.webp"
    },
    "width": 640,
    "height": 640
  },
  "door-diya-dark": {
    "avif": {
      "256": "door-diya-dark-256.0c8fe6ce.avif",
      "640": "door-diya-dark-640.f9aea467.avif"
    },
    "webp": {
      "256": "door-diya-dark-256.42979818.webp",
      "640": "door-diya-dark-640.6af16daf.webp"
    },
    "width": 640,
    "height": 640
  },
  "door-diya": {
    "avif": {
      "256": "door-diya-256.d2c5f53b.avif",
      "640": "door-diya-640.0c66eb7e.avif"
    },
    "webp": {
      "256": "door-diya-256.76595c63.webp",
      "640": "door-diya-640.9e6badc8.webp"
    },
    "width": 640,
    "height": 640
  },
  "door-journal-dark": {
    "avif": {
      "256": "door-journal-dark-256.825f1678.avif",
      "640": "door-journal-dark-640.52b859a0.avif"
    },
    "webp": {
      "256": "door-journal-dark-256.ffa416b1.webp",
      "640": "door-journal-dark-640.e8514fbc.webp"
    },
    "width": 640,
    "height": 640
  },
  "door-journal": {
    "avif": {
      "256": "door-journal-256.8ab30c96.avif",
      "640": "door-journal-640.2b3f9619.avif"
    },
    "webp": {
      "256": "door-journal-256.566a6fc3.webp",
      "640": "door-journal-640.ff0c500c.webp"
    },
    "width": 640,
    "height": 640
  },
  "door-mindgym-dark": {
    "avif": {
      "256": "door-mindgym-dark-256.554fc954.avif",
      "640": "door-mindgym-dark-640.94d64760.avif"
    },
    "webp": {
      "256": "door-mindgym-dark-256.5e45bef2.webp",
      "640": "door-mindgym-dark-640.0d5168e0.webp"
    },
    "width": 640,
    "height": 640
  },
  "door-mindgym": {
    "avif": {
      "256": "door-mindgym-256.a4894b56.avif",
      "640": "door-mindgym-640.be4bcc4a.avif"
    },
    "webp": {
      "256": "door-mindgym-256.59180e3d.webp",
      "640": "door-mindgym-640.bd76eaf6.webp"
    },
    "width": 640,
    "height": 640
  },
  "door-peer-dark": {
    "avif": {
      "256": "door-peer-dark-256.ca2898f6.avif",
      "640": "door-peer-dark-640.e6f71ce3.avif"
    },
    "webp": {
      "256": "door-peer-dark-256.a41f91ce.webp",
      "640": "door-peer-dark-640.845b03a0.webp"
    },
    "width": 640,
    "height": 640
  },
  "door-peer": {
    "avif": {
      "256": "door-peer-256.2c6cc802.avif",
      "640": "door-peer-640.91ac4724.avif"
    },
    "webp": {
      "256": "door-peer-256.96a3ce3b.webp",
      "640": "door-peer-640.2ccc53c0.webp"
    },
    "width": 640,
    "height": 640
  },
  "door-practice-breath": {
    "avif": {
      "256": "door-practice-breath-256.6b97cbee.avif",
      "640": "door-practice-breath-640.0c663e46.avif"
    },
    "webp": {
      "256": "door-practice-breath-256.e7a5d71b.webp",
      "640": "door-practice-breath-640.4d7b3d6e.webp"
    },
    "width": 640,
    "height": 480
  },
  "door-practice-drift": {
    "avif": {
      "256": "door-practice-drift-256.655b7939.avif",
      "640": "door-practice-drift-640.94f116ef.avif"
    },
    "webp": {
      "256": "door-practice-drift-256.fb771f51.webp",
      "640": "door-practice-drift-640.960f0930.webp"
    },
    "width": 640,
    "height": 480
  },
  "door-reads-dark": {
    "avif": {
      "256": "door-reads-dark-256.f689a0e7.avif",
      "640": "door-reads-dark-640.e6aa2cdc.avif"
    },
    "webp": {
      "256": "door-reads-dark-256.55d442cb.webp",
      "640": "door-reads-dark-640.0c75ffb4.webp"
    },
    "width": 640,
    "height": 640
  },
  "door-reads": {
    "avif": {
      "256": "door-reads-256.e9c64af5.avif",
      "640": "door-reads-640.ed09ebbb.avif"
    },
    "webp": {
      "256": "door-reads-256.53502eea.webp",
      "640": "door-reads-640.96a417e9.webp"
    },
    "width": 640,
    "height": 640
  },
  "hero-landscape-afternoon": {
    "avif": {
      "640": "hero-landscape-afternoon-640.7981b4b8.avif",
      "1264": "hero-landscape-afternoon-1264.8914f1c8.avif"
    },
    "webp": {
      "640": "hero-landscape-afternoon-640.b1ae8423.webp",
      "1264": "hero-landscape-afternoon-1264.9325ea3e.webp"
    },
    "width": 1264,
    "height": 848
  },
  "hero-landscape-evening": {
    "avif": {
      "640": "hero-landscape-evening-640.95f613a4.avif",
      "1264": "hero-landscape-evening-1264.d15a87a1.avif"
    },
    "webp": {
      "640": "hero-landscape-evening-640.1fd6125e.webp",
      "1264": "hero-landscape-evening-1264.70037779.webp"
    },
    "width": 1264,
    "height": 843
  },
  "hero-landscape-morning": {
    "avif": {
      "640": "hero-landscape-morning-640.3a37c55d.avif",
      "1264": "hero-landscape-morning-1264.1a7cbc93.avif"
    },
    "webp": {
      "640": "hero-landscape-morning-640.a273001e.webp",
      "1264": "hero-landscape-morning-1264.d02fe380.webp"
    },
    "width": 1264,
    "height": 848
  },
  "hero-landscape-night": {
    "avif": {
      "640": "hero-landscape-night-640.e193316b.avif",
      "1264": "hero-landscape-night-1264.8c7ea1f2.avif"
    },
    "webp": {
      "640": "hero-landscape-night-640.06ed7de8.webp",
      "1264": "hero-landscape-night-1264.67e08ae4.webp"
    },
    "width": 1264,
    "height": 848
  }
} as const satisfies Record<string, RiverImageEntry>;

export type RiverImageName = keyof typeof RIVER_MANIFEST;
