import {
  Wind,
  Brain,
  Compass,
  Lock,
  CloudSun,
  Hand,
  Gavel,
  Flower2,
  Timer,
  Palette,
  Smile,
  Grid3x3,
  Crown,
  Gamepad2,
  Film,
} from "lucide-react";
import type { MindGymTool, BadgeDefinition, MindGymSection } from "./types";

export const MINDGYM_TOOLS: readonly MindGymTool[] = [
  {
    id: "breath-sphere",
    title: "Breath Sphere",
    shortDesc: "Guided breathing with a living, animated sphere",
    clinicalTag: "Anxiety Relief",
    clinicalBasis: "Diaphragmatic breathing activates the parasympathetic nervous system, lowering cortisol and improving heart rate variability (HRV).",
    minutes: 3,
    xp: 20,
    icon: Wind,
    gradient: ["#0d9488", "#06b6d4"] as const,
    section: "calm",
  },
  {
    id: "thought-trap",
    title: "Thought Trap",
    shortDesc: "Catch and reframe cognitive distortions",
    clinicalTag: "CBT",
    clinicalBasis: "Aaron Beck's cognitive restructuring helps identify distorted thinking patterns and replace them with balanced, evidence-based thoughts.",
    minutes: 5,
    xp: 40,
    icon: Brain,
    gradient: ["#7c3aed", "#a78bfa"] as const,
    section: "reflect",
  },
  {
    id: "emotion-compass",
    title: "Emotion Compass",
    shortDesc: "Map your feelings on an interactive emotion wheel",
    clinicalTag: "Emotional Awareness",
    clinicalBasis: "Emotional granularity research (Lisa Feldman Barrett) shows that precisely labeling emotions reduces amygdala reactivity and improves regulation.",
    minutes: 2,
    xp: 15,
    icon: Compass,
    gradient: ["#e11d48", "#f97316"] as const,
    section: "reflect",
  },
  {
    id: "worry-vault",
    title: "Worry Vault",
    shortDesc: "Lock worries away and review them with clarity",
    clinicalTag: "ACT Defusion",
    clinicalBasis: "Scheduled worry (ACT cognitive defusion) reduces rumination by containing worries to a specific time, breaking the anxiety loop.",
    minutes: 3,
    xp: 35,
    icon: Lock,
    gradient: ["#1e40af", "#3b82f6"] as const,
    section: "reflect",
  },
  {
    id: "mood-weather",
    title: "Mood Weather",
    shortDesc: "Daily mood + energy check-in as weather",
    clinicalTag: "Mood Tracking",
    clinicalBasis: "Behavioral activation and mood monitoring help identify patterns, predict low periods, and guide timely interventions.",
    minutes: 1,
    xp: 10,
    icon: CloudSun,
    gradient: ["#ca8a04", "#facc15"] as const,
    section: "energize",
  },
  {
    id: "five-senses",
    title: "5-4-3-2-1 Anchor",
    shortDesc: "Sensory grounding to return to the present",
    clinicalTag: "Grounding",
    clinicalBasis: "DBT sensory anchoring interrupts dissociation and panic by redirecting attention to immediate physical experience.",
    minutes: 4,
    xp: 25,
    icon: Hand,
    gradient: ["#059669", "#34d399"] as const,
    section: "calm",
  },
  {
    id: "inner-critic",
    title: "Inner Critic Court",
    shortDesc: "Put your inner critic on trial with self-compassion",
    clinicalTag: "Self-Compassion",
    clinicalBasis: "Kristin Neff's self-compassion therapy reduces shame-driven thinking by developing an internal compassionate voice.",
    minutes: 5,
    xp: 45,
    icon: Gavel,
    gradient: ["#9333ea", "#c084fc"] as const,
    section: "reflect",
  },
  {
    id: "gratitude-garden",
    title: "Gratitude Garden",
    shortDesc: "Grow a garden with daily gratitude entries",
    clinicalTag: "Positive Psychology",
    clinicalBasis: "Gratitude journaling (Emmons & McCullough, 2003) increases well-being, reduces depression, and improves sleep quality.",
    minutes: 3,
    xp: 30,
    icon: Flower2,
    gradient: ["#16a34a", "#4ade80"] as const,
    section: "energize",
  },
  {
    id: "focus-flow",
    title: "Focus Flow Timer",
    shortDesc: "Pomodoro timer with mood check-ins and breaks",
    clinicalTag: "Focus & Flow",
    clinicalBasis: "Time-boxing reduces anxiety about large tasks (behavioral activation), while structured breaks prevent burnout and maintain flow states.",
    minutes: 25,
    xp: 10,
    icon: Timer,
    gradient: ["#dc2626", "#f87171"] as const,
    section: "focus",
  },
  {
    id: "color-me-mindful",
    title: "Color Me Mindful",
    shortDesc: "A calming coloring canvas with guided pause flow",
    clinicalTag: "Creative Grounding",
    clinicalBasis: "Creative coloring can lower cognitive load, regulate breath rhythm, and support present-moment attention through repetitive, low-pressure action.",
    minutes: 7,
    xp: 30,
    icon: Palette,
    gradient: ["#f59e0b", "#f97316"] as const,
    section: "calm",
  },
  {
    id: "emotion-match",
    title: "Emotion Detective",
    shortDesc: "Read facial expressions and label what you see",
    clinicalTag: "Emotional Awareness",
    clinicalBasis: "Affect labeling research (Lieberman et al.) shows that naming observed emotions engages prefrontal regulation and reduces amygdala reactivity.",
    minutes: 4,
    xp: 30,
    icon: Smile,
    gradient: ["#0d9488", "#5eead4"] as const,
    section: "reflect",
  },
  {
    id: "memory-challenge",
    title: "Memory Challenge",
    shortDesc: "Recall a growing sequence of lights to anchor focus",
    clinicalTag: "Working Memory",
    clinicalBasis: "Sequential recall tasks engage working memory and selective attention; brief, structured practice supports cognitive flexibility under stress.",
    minutes: 5,
    xp: 35,
    icon: Grid3x3,
    gradient: ["#0891b2", "#22d3ee"] as const,
    section: "focus",
  },
  {
    id: "campus-chess",
    title: "Campus Chess",
    shortDesc: "Play chess with Indian college archetypes — solo or vs the campus AI",
    clinicalTag: "Cognitive Break",
    clinicalBasis: "Chess trains working memory, planning, and strategic thinking. A structured playful break reduces mental fatigue and restores focus.",
    minutes: 15,
    xp: 50,
    icon: Crown,
    gradient: ["#b45309", "#d97706"] as const,
    section: "fun",
  },
  {
    id: "campus-ludo",
    title: "Campus Ludo · Hostel Hustle",
    shortDesc: "A boxed board game of survival, samosas & semesters — roll, hustle, graduate",
    clinicalTag: "Cognitive Break",
    clinicalBasis: "Light cognitive break. Dice + stance choices + quick mini-games engage attention, planning and emotion regulation in a low-stakes, playful frame.",
    minutes: 15,
    xp: 50,
    icon: Crown,
    gradient: ["#7c2d12", "#ea580c"] as const,
    section: "fun",
  },
  {
    id: "buddy-tictactoe",
    title: "Buddy Match",
    shortDesc: "Tic-tac-toe vs a 3D animated buddy — he reacts to every move",
    clinicalTag: "Cognitive Break",
    clinicalBasis: "A short playful break with a reactive companion triggers mild positive affect and keeps attention focused. The companion's emotional expressiveness adds a social dimension that amplifies mood benefit.",
    minutes: 5,
    xp: 50,
    icon: Gamepad2,
    gradient: ["#0f766e", "#14b8a6"] as const,
    section: "fun",
  },
  {
    id: "read-my-mood",
    title: "Read My Mood",
    shortDesc: "Your 3D buddy acts out a feeling — can you name it?",
    clinicalTag: "Emotional Awareness",
    clinicalBasis: "Reading emotion from a face is affect recognition — the front half of affect labeling (Lieberman et al.). Naming what another is feeling strengthens the same emotional-granularity skill that supports self-regulation, wrapped in a light, playful round.",
    minutes: 4,
    xp: 30,
    icon: Film,
    gradient: ["#9333ea", "#c084fc"] as const,
    section: "fun",
  },
] as const;

export const MINDGYM_SECTIONS: readonly MindGymSection[] = [
  { id: "calm", title: "Calm", blurb: "Breath, grounding, softening.", tone: "sage" },
  { id: "focus", title: "Focus", blurb: "Gather attention. One thing.", tone: "warmth" },
  { id: "reflect", title: "Reflect", blurb: "Quiet writing prompts.", tone: "sage" },
  { id: "energize", title: "Energize", blurb: "Small, honest lifts.", tone: "warmth" },
  { id: "fun", title: "Fun", blurb: "Play, recharge, enjoy.", tone: "warmth" },
] as const;

export function getToolsBySection(sectionId: MindGymSection["id"]): readonly MindGymTool[] {
  return MINDGYM_TOOLS.filter((t) => t.section === sectionId);
}

export const BADGES: readonly BadgeDefinition[] = [
  { id: "first-breath", title: "First Breath", description: "Complete Breath Sphere once", requirement: "breath-sphere:1", icon: "🌬️" },
  { id: "week-warrior", title: "Week Warrior", description: "Maintain a 7-day streak", requirement: "streak:7", icon: "🔥" },
  { id: "thought-architect", title: "Thought Architect", description: "Complete Thought Trap 10 times", requirement: "thought-trap:10", icon: "🧠" },
  { id: "garden-keeper", title: "Garden Keeper", description: "Plant 30 gratitude entries", requirement: "gratitude-garden:30", icon: "🌻" },
  { id: "deep-roots", title: "Deep Roots", description: "Maintain a 30-day streak", requirement: "streak:30", icon: "🌳" },
  { id: "midnight-mitra", title: "Midnight Mitra", description: "Complete a practice between 11 PM and 4 AM", requirement: "midnight:1", icon: "🌙" },
] as const;

export function getToolById(id: string): MindGymTool | undefined {
  return MINDGYM_TOOLS.find((t) => t.id === id);
}
