import {
  Wind,
  Brain,
  Compass,
  Lock,
  CloudSun,
  Hand,
  Gavel,
  Flower2,
  Timer,
} from "lucide-react";
import type { MindGymTool, BadgeDefinition } from "./types";

export const MINDGYM_TOOLS: readonly MindGymTool[] = [
  {
    id: "breath-sphere",
    title: "Breath Sphere",
    shortDesc: "Guided breathing with a living, animated sphere",
    clinicalTag: "Anxiety Relief",
    clinicalBasis: "Diaphragmatic breathing activates the parasympathetic nervous system, lowering cortisol and improving heart rate variability (HRV).",
    minutes: 3,
    xp: 20,
    icon: Wind,
    gradient: ["#0d9488", "#06b6d4"] as const,
  },
  {
    id: "thought-trap",
    title: "Thought Trap",
    shortDesc: "Catch and reframe cognitive distortions",
    clinicalTag: "CBT",
    clinicalBasis: "Aaron Beck's cognitive restructuring helps identify distorted thinking patterns and replace them with balanced, evidence-based thoughts.",
    minutes: 5,
    xp: 40,
    icon: Brain,
    gradient: ["#7c3aed", "#a78bfa"] as const,
  },
  {
    id: "emotion-compass",
    title: "Emotion Compass",
    shortDesc: "Map your feelings on an interactive emotion wheel",
    clinicalTag: "Emotional Awareness",
    clinicalBasis: "Emotional granularity research (Lisa Feldman Barrett) shows that precisely labeling emotions reduces amygdala reactivity and improves regulation.",
    minutes: 2,
    xp: 15,
    icon: Compass,
    gradient: ["#e11d48", "#f97316"] as const,
  },
  {
    id: "worry-vault",
    title: "Worry Vault",
    shortDesc: "Lock worries away and review them with clarity",
    clinicalTag: "ACT Defusion",
    clinicalBasis: "Scheduled worry (ACT cognitive defusion) reduces rumination by containing worries to a specific time, breaking the anxiety loop.",
    minutes: 3,
    xp: 35,
    icon: Lock,
    gradient: ["#1e40af", "#3b82f6"] as const,
  },
  {
    id: "mood-weather",
    title: "Mood Weather",
    shortDesc: "Daily mood + energy check-in as weather",
    clinicalTag: "Mood Tracking",
    clinicalBasis: "Behavioral activation and mood monitoring help identify patterns, predict low periods, and guide timely interventions.",
    minutes: 1,
    xp: 10,
    icon: CloudSun,
    gradient: ["#ca8a04", "#facc15"] as const,
  },
  {
    id: "five-senses",
    title: "5-4-3-2-1 Anchor",
    shortDesc: "Sensory grounding to return to the present",
    clinicalTag: "Grounding",
    clinicalBasis: "DBT sensory anchoring interrupts dissociation and panic by redirecting attention to immediate physical experience.",
    minutes: 4,
    xp: 25,
    icon: Hand,
    gradient: ["#059669", "#34d399"] as const,
  },
  {
    id: "inner-critic",
    title: "Inner Critic Court",
    shortDesc: "Put your inner critic on trial with self-compassion",
    clinicalTag: "Self-Compassion",
    clinicalBasis: "Kristin Neff's self-compassion therapy reduces shame-driven thinking by developing an internal compassionate voice.",
    minutes: 5,
    xp: 45,
    icon: Gavel,
    gradient: ["#9333ea", "#c084fc"] as const,
  },
  {
    id: "gratitude-garden",
    title: "Gratitude Garden",
    shortDesc: "Grow a garden with daily gratitude entries",
    clinicalTag: "Positive Psychology",
    clinicalBasis: "Gratitude journaling (Emmons & McCullough, 2003) increases well-being, reduces depression, and improves sleep quality.",
    minutes: 3,
    xp: 30,
    icon: Flower2,
    gradient: ["#16a34a", "#4ade80"] as const,
  },
  {
    id: "focus-flow",
    title: "Focus Flow Timer",
    shortDesc: "Pomodoro timer with mood check-ins and breaks",
    clinicalTag: "Focus & Flow",
    clinicalBasis: "Time-boxing reduces anxiety about large tasks (behavioral activation), while structured breaks prevent burnout and maintain flow states.",
    minutes: 25,
    xp: 10,
    icon: Timer,
    gradient: ["#dc2626", "#f87171"] as const,
  },
] as const;

export const BADGES: readonly BadgeDefinition[] = [
  { id: "first-breath", title: "First Breath", description: "Complete Breath Sphere once", requirement: "breath-sphere:1", icon: "🌬️" },
  { id: "week-warrior", title: "Week Warrior", description: "Maintain a 7-day streak", requirement: "streak:7", icon: "🔥" },
  { id: "thought-architect", title: "Thought Architect", description: "Complete Thought Trap 10 times", requirement: "thought-trap:10", icon: "🧠" },
  { id: "garden-keeper", title: "Garden Keeper", description: "Plant 30 gratitude entries", requirement: "gratitude-garden:30", icon: "🌻" },
  { id: "deep-roots", title: "Deep Roots", description: "Maintain a 30-day streak", requirement: "streak:30", icon: "🌳" },
  { id: "midnight-mitra", title: "Midnight Mitra", description: "Complete a practice between 11 PM and 4 AM", requirement: "midnight:1", icon: "🌙" },
] as const;

export function getToolById(id: string): MindGymTool | undefined {
  return MINDGYM_TOOLS.find((t) => t.id === id);
}
