/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useRef, useState } from "react";

import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

const corresponding = {
  A: "viseme_PP",   // Closed mouth (p, b, m)
  B: "viseme_kk",   // Clenched teeth
  C: "viseme_I",    // Open mouth (vowels)
  D: "viseme_AA",   // Wide open mouth
  E: "viseme_O",    // Rounded mouth
  F: "viseme_U",    // Puckered lips
  G: "viseme_FF",   // F/V sounds
  H: "viseme_TH",   // Tongue/L sounds
  X: "viseme_PP",   // Rest/pause - closed mouth (natural resting position)
};

let setupMode = false;

export function Avatar(props) {
  const { nodes, materials, scene } = useGLTF(
    "/models/68c43859d830ce77ae036e51.glb"
  );

  const { message, onMessagePlayed, chat } = useChat();

  const [lipsync, setLipsync] = useState();
  const [playbackTime, setPlaybackTime] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);

  useEffect(() => {
    console.log('🎭 [Avatar] New message received:', message);
    if (!message) {
      setAnimation("Idle");
      setIsPlaying(false);
      setPlaybackTime(0);
      return;
    }
    
    setAnimation(message.animation || "Talking_0");
    setFacialExpression(message.facialExpression || "default");
    setLipsync(message.lipsync);
    setPlaybackTime(0);
    setIsPlaying(true);
    
    // Analyze text for head movements and micro-expressions
    if (message.text) {
      analyzeTextForMovements(message.text);
    }
    
    // Handle audio playback if available
    if (message.audio && typeof message.audio === 'string') {
      console.log('🔊 [Avatar] Playing audio');
      console.log('📊 [Avatar] Audio data length:', message.audio.length, 'chars');
      try {
        // Detect audio format - Google Cloud TTS outputs WAV, gTTS outputs MP3
        // WAV files in base64 start with "UklGR" (RIFF header)
        const isWav = message.audio.startsWith('UklGR');
        const audioMimeType = isWav ? 'audio/wav' : 'audio/mp3';
        console.log('🎵 [Avatar] Detected audio format:', audioMimeType);
        
        const audio = new Audio(`data:${audioMimeType};base64,` + message.audio);
        audio.play().catch(err => {
          console.error('❌ [Avatar] Audio playback failed:', err);
          console.log('⚠️ [Avatar] Falling back to timer-based playback');
          simulatePlaybackDuration();
        });
        setAudio(audio);
        audio.onended = () => {
          console.log('✅ [Avatar] Audio playback complete');
          setIsPlaying(false);
          onMessagePlayed();
        };
      } catch (error) {
        console.error('❌ [Avatar] Audio creation failed:', error);
        console.log('⚠️ [Avatar] Falling back to timer-based duration');
        // Fallback to timer-based duration
        simulatePlaybackDuration();
      }
    } else {
      console.log('⏱️ [Avatar] No audio - using timer-based simulation');
      // No audio - use timer-based duration simulation
      simulatePlaybackDuration();
    }
  }, [message]);
  
  // Simulate playback duration based on text length
  const simulatePlaybackDuration = () => {
    if (!message || !message.lipsync) return;
    
    // Calculate duration from lipsync data
    const mouthCues = message.lipsync.mouthCues || [];
    const duration = mouthCues.length > 0 
      ? mouthCues[mouthCues.length - 1].end 
      : message.text.length * 0.08; // Fallback: 80ms per character
    
    console.log(`⏱️ [Avatar] Simulated duration: ${duration.toFixed(2)}s for ${message.text.length} chars`);
    
    setTimeout(() => {
      console.log('✅ [Avatar] Simulated playback complete');
      setIsPlaying(false);
      onMessagePlayed();
    }, duration * 1000);
  };

  const { animations } = useGLTF("/models/animations.glb");

  const group = useRef();
  
  // Analyze text for head movements and micro-expressions
  const analyzeTextForMovements = (text) => {
    console.log('🧠 [Avatar] Analyzing text for movements:', text?.substring(0, 50));
    
    if (!text) {
      console.warn('⚠️ [Avatar] No text provided for movement analysis');
      return;
    }
    
    // Check for questions (eyebrow raise + head tilt up)
    if (text.includes('?')) {
      console.log('❓ [Avatar] Question detected - tilting head up + eyebrow raise');
      headRef.current.pitch = 0.08; // Slight upward tilt
      microExpressionRef.current.active = true;
      microExpressionRef.current.endTime = Date.now() + 300; // 0.3s duration
    }
    // Check for statements (slight nod down)
    else if (text.includes('.') || text.includes('!')) {
      console.log('💬 [Avatar] Statement detected - nodding head down');
      headRef.current.pitch = -0.05; // Slight downward nod
    }
    
    // Reset head movement after duration
    setTimeout(() => {
      headRef.current.pitch = 0;
      headRef.current.roll = 0;
    }, 800);
  };
  const { actions, mixer } = useAnimations(animations, group);
  const [animation, setAnimation] = useState(
    animations.find((a) => a.name === "Idle") ? "Idle" : animations[0].name // Check if Idle animation exists otherwise use first animation
  );
  useEffect(() => {
    actions[animation]
      .reset()
      .fadeIn(mixer.stats.actions.inUse === 0 ? 0 : 0.5)
      .play();
    return () => actions[animation].fadeOut(0.5);
  }, [animation]);

  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

        if (!setupMode) {
          try {
            set({
              [target]: value,
            });
          } catch (e) {}
        }
      }
    });
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");
  const [audio, setAudio] = useState();
  
  // ===== NATURAL EYE MOVEMENT SYSTEM =====
  const [eyeTarget, setEyeTarget] = useState({ x: 0, y: 0 });
  const eyeRef = useRef({ currentX: 0, currentY: 0, nextChangeTime: 0 });
  
  // ===== IDLE BREATHING SYSTEM =====
  const breathingRef = useRef({ time: 0 });
  
  // ===== HEAD MOVEMENT SYSTEM =====
  const headRef = useRef({ pitch: 0, yaw: 0, roll: 0, yawTime: 0 });
  
  // ===== MICRO-EXPRESSIONS SYSTEM =====
  const microExpressionRef = useRef({ active: false, endTime: 0 });

  useFrame((state, delta) => {
    // ===== FACIAL EXPRESSIONS =====
    !setupMode &&
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        // Exclude eye look targets (handled by natural eye movement)
        if (key.startsWith("eyeLook")) {
          return;
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });

    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);
    
    // ===== NATURAL EYE MOVEMENT =====
    if (!setupMode) {
      const currentTime = state.clock.elapsedTime;
      
      // Generate new eye target every 2-4 seconds
      if (currentTime >= eyeRef.current.nextChangeTime) {
        const horizontalRange = 0.3; // ~15-20 degrees
        const verticalRange = 0.2;   // ~10-15 degrees
        
        setEyeTarget({
          x: (Math.random() - 0.5) * horizontalRange,
          y: (Math.random() - 0.5) * verticalRange
        });
        
        eyeRef.current.nextChangeTime = currentTime + THREE.MathUtils.randFloat(2, 4);
      }
      
      // Smooth interpolation to target (Perlin-like smoothness)
      eyeRef.current.currentX = THREE.MathUtils.lerp(
        eyeRef.current.currentX,
        eyeTarget.x,
        0.05 // Slow, smooth transitions
      );
      eyeRef.current.currentY = THREE.MathUtils.lerp(
        eyeRef.current.currentY,
        eyeTarget.y,
        0.05
      );
      
      // Apply to eye morph targets (with safe fallback)
      try {
        lerpMorphTarget("eyeLookOutLeft", Math.max(0, -eyeRef.current.currentX), 0.1);
        lerpMorphTarget("eyeLookInLeft", Math.max(0, eyeRef.current.currentX), 0.1);
        lerpMorphTarget("eyeLookOutRight", Math.max(0, eyeRef.current.currentX), 0.1);
        lerpMorphTarget("eyeLookInRight", Math.max(0, -eyeRef.current.currentX), 0.1);
        lerpMorphTarget("eyeLookUpLeft", Math.max(0, eyeRef.current.currentY), 0.1);
        lerpMorphTarget("eyeLookUpRight", Math.max(0, eyeRef.current.currentY), 0.1);
        lerpMorphTarget("eyeLookDownLeft", Math.max(0, -eyeRef.current.currentY), 0.1);
        lerpMorphTarget("eyeLookDownRight", Math.max(0, -eyeRef.current.currentY), 0.1);
      } catch (error) {
        // Only log error once
        if (!eyeRef.current.warnedMorphError) {
          console.error('⚠️ [Avatar] Eye morph targets not available:', error);
          eyeRef.current.warnedMorphError = true;
        }
      }
    }
    
    // ===== IDLE BREATHING ANIMATION =====
    if (!setupMode && group.current) {
      breathingRef.current.time += delta;
      
      // Breathing: 12 breaths/min = 0.2Hz = 5 second period
      const breathingCycle = Math.sin(breathingRef.current.time * 0.2 * Math.PI * 2);
      const breathingAmount = 0.007; // 0.5-1% scale change
      
      // Apply to chest/spine (Hips node for simplicity)
      if (nodes.Hips) {
        // Store original scale if not already stored
        if (!breathingRef.current.originalScaleY) {
          breathingRef.current.originalScaleY = nodes.Hips.scale.y;
        }
        nodes.Hips.scale.y = breathingRef.current.originalScaleY + breathingAmount * breathingCycle;
      } else {
        // Only log warning once
        if (!breathingRef.current.warnedNoHips) {
          console.warn('⚠️ [Avatar] nodes.Hips not found - breathing animation disabled');
          breathingRef.current.warnedNoHips = true;
        }
      }
    }
    
    // ===== HEAD MOVEMENT SYSTEM =====
    if (!setupMode && group.current && isPlaying) {
      // Gentle yaw (side-to-side) during talking using Perlin-like noise
      headRef.current.yawTime += delta;
      const yawNoise = Math.sin(headRef.current.yawTime * 0.5) * Math.cos(headRef.current.yawTime * 0.3);
      headRef.current.yaw = yawNoise * 0.08; // ±5-10 degrees
      
      // Combine roll with yaw for natural emphasis
      headRef.current.roll = yawNoise * 0.03; // Slight tilt
      
      // Apply head rotation
      if (nodes.Head) {
        nodes.Head.rotation.x = THREE.MathUtils.lerp(nodes.Head.rotation.x, headRef.current.pitch, 0.1);
        nodes.Head.rotation.y = THREE.MathUtils.lerp(nodes.Head.rotation.y, headRef.current.yaw, 0.08);
        nodes.Head.rotation.z = THREE.MathUtils.lerp(nodes.Head.rotation.z, headRef.current.roll, 0.08);
      } else {
        console.warn('⚠️ [Avatar] nodes.Head not found - head movements disabled');
      }
    } else if (!setupMode && group.current && nodes.Head) {
      // Return to neutral when idle
      nodes.Head.rotation.x = THREE.MathUtils.lerp(nodes.Head.rotation.x, 0, 0.05);
      nodes.Head.rotation.y = THREE.MathUtils.lerp(nodes.Head.rotation.y, 0, 0.05);
      nodes.Head.rotation.z = THREE.MathUtils.lerp(nodes.Head.rotation.z, 0, 0.05);
    }
    
    // ===== MICRO-EXPRESSIONS =====
    if (!setupMode && microExpressionRef.current.active) {
      // Eyebrow raise on questions (quick 0.3s transition)
      // Only apply if not overridden by facial expression preset
      const currentFacialExp = facialExpressions[facialExpression];
      const hasExistingBrowValue = currentFacialExp && currentFacialExp.browInnerUp !== undefined;
      
      if (Date.now() < microExpressionRef.current.endTime) {
        if (!hasExistingBrowValue) {
          lerpMorphTarget("browInnerUp", 0.5, 0.3);
        }
        // Skip micro-expression if facial expression already controls eyebrows
      } else {
        microExpressionRef.current.active = false;
        if (!hasExistingBrowValue) {
          lerpMorphTarget("browInnerUp", 0, 0.2);
        }
      }
    }

    // ===== LIPSYNC =====
    if (setupMode) {
      return;
    }
    
    // Update playback time for timer-based lip-sync
    if (isPlaying && !audio) {
      setPlaybackTime(prev => prev + 0.016); // ~60fps increment
    }

    const appliedMorphTargets = [];
    if (message && lipsync && lipsync.mouthCues && Array.isArray(lipsync.mouthCues)) {
      // Use audio time if available, otherwise use playback timer
      const currentTime = audio ? audio.currentTime : playbackTime;
      
      for (let i = 0; i < lipsync.mouthCues.length; i++) {
        const mouthCue = lipsync.mouthCues[i];
        if (
          mouthCue &&
          typeof mouthCue.start === 'number' &&
          typeof mouthCue.end === 'number' &&
          mouthCue.value &&
          currentTime >= mouthCue.start &&
          currentTime <= mouthCue.end
        ) {
          const viseme = corresponding[mouthCue.value];
          if (viseme) {
            appliedMorphTargets.push(viseme);
            lerpMorphTarget(viseme, 1, 0.35);
            break;
          }
        }
      }
    }

    Object.values(corresponding).forEach((value) => {
      if (appliedMorphTargets.includes(value)) {
        return;
      }
      lerpMorphTarget(value, 0, 0.1);
    });
  });

  useControls("FacialExpressions", {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: animations.map((a) => a.name),
      onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      const emotionValues = {};
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[
            nodes.EyeLeft.morphTargetDictionary[key]
          ];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });

  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min: nodes.EyeLeft.morphTargetInfluences[
              nodes.EyeLeft.morphTargetDictionary[key]
            ],
            max: 1,
            onChange: (val) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      })
    )
  );

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  return (
    <group dispose={null} ref={group} position={[-0.09, 0.29, 0]} scale={0.88}  rotation={[0, 0.2, 0]}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="Wolf3D_Body"
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Top"
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Hair"
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/68c43859d830ce77ae036e51.glb");
useGLTF.preload("/models/animations.glb");
