// Generated by scripts/optimize-forest-backdrops.mjs — do not edit by hand.
// Re-run the script after changing the source art in art-source/mindgym-forest/.

import f1_avif_960 from "./1-960.76836059.avif";
import f1_avif_1600 from "./1-1600.10a215aa.avif";
import f1_webp_960 from "./1-960.ec21af4e.webp";
import f1_webp_1600 from "./1-1600.b0df5aa0.webp";
import f1_jpeg_1600 from "./1-1600.a6b7e2f3.jpg";
import f2_avif_960 from "./2-960.5764a3f6.avif";
import f2_avif_1600 from "./2-1600.a4380ad3.avif";
import f2_webp_960 from "./2-960.6ecb40ec.webp";
import f2_webp_1600 from "./2-1600.05d8861f.webp";
import f2_jpeg_1600 from "./2-1600.8ec533ee.jpg";
import f3_avif_960 from "./3-960.f3dec79c.avif";
import f3_avif_1600 from "./3-1600.edf2785c.avif";
import f3_webp_960 from "./3-960.4a0d6b4c.webp";
import f3_webp_1600 from "./3-1600.8b628a63.webp";
import f3_jpeg_1600 from "./3-1600.23324e84.jpg";
import f4_avif_960 from "./4-960.e72bafa8.avif";
import f4_avif_1600 from "./4-1600.a3704510.avif";
import f4_webp_960 from "./4-960.eb7cd23f.webp";
import f4_webp_1600 from "./4-1600.5874d302.webp";
import f4_jpeg_1600 from "./4-1600.a12ddd0e.jpg";
import f5_avif_960 from "./5-960.740d0da4.avif";
import f5_avif_1600 from "./5-1600.605edb39.avif";
import f5_webp_960 from "./5-960.0bf73474.webp";
import f5_webp_1600 from "./5-1600.fb697b71.webp";
import f5_jpeg_1600 from "./5-1600.d818e6d8.jpg";
import f6_avif_960 from "./6-960.78663a4c.avif";
import f6_avif_1600 from "./6-1600.7ff47f59.avif";
import f6_webp_960 from "./6-960.6a1b6f54.webp";
import f6_webp_1600 from "./6-1600.089775b5.webp";
import f6_jpeg_1600 from "./6-1600.90943869.jpg";
import f7_avif_960 from "./7-960.25af4884.avif";
import f7_avif_1600 from "./7-1600.6c88b230.avif";
import f7_webp_960 from "./7-960.62d67483.webp";
import f7_webp_1600 from "./7-1600.bc3aab2a.webp";
import f7_jpeg_1600 from "./7-1600.24b75122.jpg";
import f8_avif_960 from "./8-960.91f900de.avif";
import f8_avif_1600 from "./8-1600.506f55f8.avif";
import f8_webp_960 from "./8-960.95b8f4de.webp";
import f8_webp_1600 from "./8-1600.36c099a8.webp";
import f8_jpeg_1600 from "./8-1600.fc5a96ce.jpg";

export const FOREST_WIDTHS = [960, 1600] as const;

export interface ForestBackdropSources {
  avif: string;
  webp: string;
  fallback: string;
  width: number;
  height: number;
}

/** srcSet strings, keyed by the backdrop's number as it appears on disk. */
export const forestBackdrops: Record<string, ForestBackdropSources> = {
  "1": { avif: `${f1_avif_960} 960w, ${f1_avif_1600} 1600w`, webp: `${f1_webp_960} 960w, ${f1_webp_1600} 1600w`, fallback: f1_jpeg_1600, width: 1600, height: 1068 },
  "2": { avif: `${f2_avif_960} 960w, ${f2_avif_1600} 1600w`, webp: `${f2_webp_960} 960w, ${f2_webp_1600} 1600w`, fallback: f2_jpeg_1600, width: 1600, height: 1067 },
  "3": { avif: `${f3_avif_960} 960w, ${f3_avif_1600} 1600w`, webp: `${f3_webp_960} 960w, ${f3_webp_1600} 1600w`, fallback: f3_jpeg_1600, width: 1600, height: 1069 },
  "4": { avif: `${f4_avif_960} 960w, ${f4_avif_1600} 1600w`, webp: `${f4_webp_960} 960w, ${f4_webp_1600} 1600w`, fallback: f4_jpeg_1600, width: 1600, height: 1099 },
  "5": { avif: `${f5_avif_960} 960w, ${f5_avif_1600} 1600w`, webp: `${f5_webp_960} 960w, ${f5_webp_1600} 1600w`, fallback: f5_jpeg_1600, width: 1600, height: 1067 },
  "6": { avif: `${f6_avif_960} 960w, ${f6_avif_1600} 1600w`, webp: `${f6_webp_960} 960w, ${f6_webp_1600} 1600w`, fallback: f6_jpeg_1600, width: 1600, height: 1067 },
  "7": { avif: `${f7_avif_960} 960w, ${f7_avif_1600} 1600w`, webp: `${f7_webp_960} 960w, ${f7_webp_1600} 1600w`, fallback: f7_jpeg_1600, width: 1600, height: 1067 },
  "8": { avif: `${f8_avif_960} 960w, ${f8_avif_1600} 1600w`, webp: `${f8_webp_960} 960w, ${f8_webp_1600} 1600w`, fallback: f8_jpeg_1600, width: 1600, height: 1067 },
};

export const FOREST_BACKDROP_NAMES = Object.keys(forestBackdrops);
